// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package router

import (
	"github.com/jinzhu/gorm"
	"github/akalitt/go-errors-example/api"
	"github/akalitt/go-errors-example/internal/repository"
	"github/akalitt/go-errors-example/internal/service"
)

// Injectors from wire.go:

func InitBookAPI(db *gorm.DB) api.TagAPI {
	tagRepository := repository.NewTagRepository(db)
	tagService := service.NewTagService(tagRepository)
	tagAPI := api.NewTagAPI(tagService)
	return tagAPI
}
